###############################################################################

[[account]]
namespace = "SchemaOneDPP"
account_id = "111111111111"
region = "us-east-1"
role_arn = "arn:aws:iam::111111111111:role/CloudWatch-CrossAccountSharingRole"

[[account]]
namespace = "SchemaOneDPP"
account_id = "222222222222"
region = "eu-west-1"
role_arn = "arn:aws:iam::222222222222:role/CloudWatch-CrossAccountSharingRole"

[[account]]
namespace = "SchemaOneDPP"
account_id = "333333333333"
region = "us-west-2"
role_arn = "arn:aws:iam::333333333333:role/CloudWatch-CrossAccountSharingRole"

###############################################################################
